#line 1 "rearrange_data.c.src"

/*
 *****************************************************************************
 **       This file was autogenerated from a template  DO NOT EDIT!!!!      **
 **       Changes should be made to the original source (.src) file         **
 *****************************************************************************
 */

#line 1
/* -*- Mode: C -*- */
/* Common code for creating GUFuncs with BLAS/Lapack
*/
/*
Adapted from https://github.com/numpy/numpy/numpy/linalg/umath_linalg.c.src
Copyright/licence info for that file:
* Copyright (c) 2005-2017, NumPy Developers.
* All rights reserved.
*
* Redistribution and use in source and binary forms, with or without
* modification, are permitted provided that the following conditions
* are met:
*   - Redistributions of source code must retain the above
*     copyright notice, this list of conditions and the
*     following disclaimer.
*   - Redistributions in binary form must reproduce the above copyright
*     notice, this list of conditions and the following disclaimer
*     in the documentation and/or other materials provided with the
*     distribution.
*   - Neither the name of the author nor the names of its
*     contributors may be used to endorse or promote products derived
*     from this software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
* "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
* A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
* OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
* LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
* DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
* THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
* (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
* OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
/*
*****************************************************************************
**                            Includes                                     **
*****************************************************************************
*/
#define NPY_NO_DEPRECATED_API NPY_API_VERSION
#include "rearrange_data.h"

/*
*****************************************************************************
**                   BLAS/Lapack calling macros                            **
*****************************************************************************
*/
#line 55

/* copy vector x into y */
extern void
FNAME(scopy)(int *n,
            float *sx, int *incx,
            float *sy, int *incy);

#if 0
/* complex conjugate */
extern void
FNAME(clacgv)(int *n, float *x, int *incx);
#endif


#line 55

/* copy vector x into y */
extern void
FNAME(dcopy)(int *n,
            double *sx, int *incx,
            double *sy, int *incy);

#if 0
/* complex conjugate */
extern void
FNAME(zlacgv)(int *n, double *x, int *incx);
#endif


#line 55

/* copy vector x into y */
extern void
FNAME(ccopy)(int *n,
            f2c_complex *sx, int *incx,
            f2c_complex *sy, int *incy);

#if 1
/* complex conjugate */
extern void
FNAME(clacgv)(int *n, f2c_complex *x, int *incx);
#endif


#line 55

/* copy vector x into y */
extern void
FNAME(zcopy)(int *n,
            f2c_doublecomplex *sx, int *incx,
            f2c_doublecomplex *sy, int *incy);

#if 1
/* complex conjugate */
extern void
FNAME(zlacgv)(int *n, f2c_doublecomplex *x, int *incx);
#endif



/*
*****************************************************************************
**                    Data rearrangement functions                         **
*****************************************************************************
*/

              /* rearranging of 2D matrices using blas */

#line 89

/*********************
*  Complex numbers   *
**********************/

fortran_int
FLOAT_real_int(fortran_real val)
{
#if 0
    return (fortran_int)val.r;
#else
    return (fortran_int)val;
#endif
}

static NPY_INLINE void
FLOAT_conj_vec(fortran_int len, float *dst, fortran_int stride,
                const LINEARIZE_DATA_t *data)
{
#if 0
    if (data->conj) {
        FNAME(clacgv)(&len, (void *)dst, &stride);
    }
#endif
}

/*********************
*  Copying matrices  *
**********************/

void
linearize_FLOAT_matrix(void *dst_in,
                        const void *src_in,
                        const LINEARIZE_DATA_t* data)
{
    float *src = (float *) src_in;
    float *dst = (float *) dst_in;

    if (dst) {
        int i, j;
        fortran_int columns = (fortran_int)data->columns;
        fortran_int column_strides =
                (fortran_int)(data->column_strides/sizeof(float));
        fortran_int one = 1;
        for (i = 0; i < data->rows; i++) {
            if (column_strides > 0) {
                FNAME(scopy)(&columns,
                              (void *)src, &column_strides,
                              (void *)dst, &one);
            }
            else if (column_strides < 0) {
                /*
                * BLAS _copy assumes dst points to the first element in memory.
                * numpy points it at the first element of the array.
                * We have to compensate.
                */
                FNAME(scopy)(  &columns,
                                (void *)((float*)src + (columns-1)*column_strides),
                                &column_strides,
                                (void *)dst, &one);
            }
            else {
                /*
                * Zero stride has undefined behavior in some BLAS
                * implementations (e.g. OSX Accelerate), so do it
                * manually
                */
                for (j = 0; j < columns; ++j) {
                    memcpy((void *)(dst + j), (void *)src, sizeof(float));
                }
            }
            FLOAT_conj_vec(columns, dst, one, data);
            src += data->row_strides/sizeof(float);
            dst += data->output_lead_dim;
        }
    }
}

void
delinearize_FLOAT_matrix(  void *dst_in,
                            const void *src_in,
                            const LINEARIZE_DATA_t* data)
{
    float *src = (float *) src_in;
    float *dst = (float *) dst_in;

    if (src) {
        int i;
        fortran_int columns = (fortran_int)data->columns;
        fortran_int column_strides =
            (fortran_int)(data->column_strides/sizeof(float));
        fortran_int one = 1;
        for (i = 0; i < data->rows; i++) {
            if (column_strides > 0) {
                FNAME(scopy)(  &columns,
                                (void *)src, &one,
                                (void *)dst, &column_strides);
                // FLOAT_conj_vec(columns, dst, column_strides, data);
            }
            else if (column_strides < 0) {
                /*
                * BLAS _copy/lacgv assume dst points to first element in memory
                * numpy points it at the first element of the array.
                * We have to compensate.
                */
                float *dst_end = dst + (columns-1)*column_strides;
                FNAME(scopy)(  &columns,
                                (void *)src, &one,
                                (void *)dst_end, &column_strides);
                // FLOAT_conj_vec(columns, dst_end, column_strides, data);
            }
            else {
                /*
                * Zero stride has undefined behavior in some BLAS
                * implementations (e.g. OSX Accelerate), so do it
                * manually
                */
                if (columns > 0) {
                    memcpy((void *)dst, (void *)(src + (columns-1)), sizeof(float));
                    // FLOAT_conj_vec(one, dst, column_strides, data);
                }
            }
            src += data->output_lead_dim;
            dst += data->row_strides/sizeof(float);
        }
    }
}

/*
This function does not fill the lower triangle with zeros.
To do that, call zero_FLOAT_matrix first.
*/
void
delinearize_FLOAT_triu(void *dst_in,
                        const void *src_in,
                        const LINEARIZE_DATA_t* data)
{
   float *src = (float *) src_in;
   float *dst = (float *) dst_in;

   if (src) {
       int i;
        fortran_int columns = (fortran_int)data->columns;
        fortran_int column_strides =
            (fortran_int)(data->column_strides/sizeof(float));
        fortran_int one = 1;
        for (i = 0; i < data->rows; i++) {
            fortran_int len = fortran_int_min(i + 1, columns);
            if (column_strides > 0) {
                FNAME(scopy)(  &len,
                                (void *)src, &one,
                                (void *)dst, &column_strides);
            }
            else if (column_strides < 0) {
                /*
                * BLAS _copy assumes dst points to the first element in memory.
                * numpy points it at the first element of the array.
                * We have to compensate.
                */
                FNAME(scopy)(  &len,
                                (void *)src, &one,
                                (void *)(dst + (len-1)*column_strides),
                                &column_strides);
            }
            else {
                /*
                * Zero stride has undefined behavior in some BLAS
                * implementations (e.g. OSX Accelerate), so do it
                * manually
                */
                if (columns > 0) {
                    memcpy((void *)dst, (void *)(src + (len-1)), sizeof(float));
                }
            }
            src += data->output_lead_dim;
            dst += data->row_strides/sizeof(float);
        }
    }
}

/*
This function does not fill the upper triangle with zeros, or set the diagonal.
To do that, call zero_FLOAT_matrix first. Unit diagonals can be set with
eye_FLOAT_matrix.
*/
void
delinearize_FLOAT_tril(void *dst_in,
                        const void *src_in,
                        const LINEARIZE_DATA_t* data)
{
   float *src = (float *) src_in;
   float *dst = (float *) dst_in;

   if (src) {
       int i;
        fortran_int columns = (fortran_int)data->columns;
        fortran_int column_strides =
            (fortran_int)(data->column_strides/sizeof(float));
        fortran_int one = 1;
        for (i = 0; i < data->rows && i < columns - 1; i++) {
            fortran_int len = columns - i - 1;
            if (len == 0) {
                continue;
            }
            if (column_strides > 0) {
                FNAME(scopy)(  &len,
                                (void *)(src + i + 1), &one,
                                (void *)(dst + (i+1)*column_strides),
                                &column_strides);
            }
            else if (column_strides < 0) {
                /*
                * BLAS _copy assumes dst points to the first element in memory.
                * numpy points it at the first element of the array.
                * We have to compensate.
                */
                FNAME(scopy)(  &len,
                                (void *)(src + i + 1), &one,
                                (void *)(dst + (columns-1)*column_strides),
                                &column_strides);
            }
            else {
                /*
                * Zero stride has undefined behavior in some BLAS
                * implementations (e.g. OSX Accelerate), so do it
                * manually
                */
                memcpy((void *)dst, (void *)(src + (columns-1)), sizeof(float));
            }
            src += data->output_lead_dim;
            dst += data->row_strides/sizeof(float);
        }
    }
}

/*********************
*  Filling matrices  *
**********************/

void
nan_FLOAT_matrix(void *dst_in, const LINEARIZE_DATA_t* data)
{
    init_constants();
    float *dst = (float *) dst_in;

    int i, j;
    ptrdiff_t cs = data->column_strides/sizeof(float);
    for (i = 0; i < data->rows; i++) {
        float *cp = dst;
        for (j = 0; j < data->columns; ++j) {
            *cp = s_nan;
            cp += cs;
        }
        dst += data->row_strides/sizeof(float);
    }
}

void
zero_FLOAT_matrix(void *dst_in, const LINEARIZE_DATA_t* data)
{
    init_constants();
    float *dst = (float *) dst_in;

    int i, j;
    ptrdiff_t cs = data->column_strides/sizeof(float);
    for (i = 0; i < data->rows; i++) {
        float *cp = dst;
        for (j = 0; j < data->columns; ++j) {
            *cp = s_zero;
            cp += cs;
        }
        dst += data->row_strides/sizeof(float);
    }
}

/*
This function does not fill the off-diagonals with zeros.
To do that, call zero_FLOAT_matrix first.
*/
void
eye_FLOAT_matrix(void *dst_in, const LINEARIZE_DATA_t* data)
{
    init_constants();
    float *dst = (float *) dst_in;

    int i;
    ptrdiff_t cs = data->column_strides/sizeof(float);
    for (i = 0; (i < data->rows) && (i < data->columns); i++) {
        *dst = s_one;
        dst += (data->row_strides/sizeof(float)) * (data->output_lead_dim + 1);
    }
}

/*********************
*      Vectors       *
**********************/

void
linearize_FLOAT_vec(void *dst_in,
                    const void *src_in,
                    const LINEARIZE_DATA_t *data)
{
    float *src = (float *) src_in;
    float *dst = (float *) dst_in;

    if (dst) {
        fortran_int len = (fortran_int)data->columns;
        fortran_int strides = (fortran_int)(data->column_strides/sizeof(float));
        fortran_int one = 1;
        if (strides > 0) {
            FNAME(scopy)(  &len,
                            (void *)src, &strides,
                            (void *)dst, &one);
        }
        else if (strides < 0) {
            /*
            * Lapack _copy assumes dst points to first element in memory
            * instead of first element of array & tries to compensate.
            * We have to undo that
            */
            FNAME(scopy)(  &len,
                            (void *)(src + (len-1)*strides), &strides,
                            (void *)dst, &one);
        }
        else {
            /*
            * Zero stride has undefined behavior in some BLAS
            * implementations (e.g. OSX Accelerate), so do it
            * manually
            */
            int j;
            for (j = 0; j < len; ++j) {
                memcpy((void *)(dst + j), (void *)src, sizeof(float));
            }
            FLOAT_conj_vec(len, dst, one, data);
        }
    }
}

void
delinearize_FLOAT_vec(void *dst_in,
                     const void *src_in,
                     const LINEARIZE_DATA_t *data)
{
    float *src = (float *) src_in;
    float *dst = (float *) dst_in;

    if (dst) {
        fortran_int len = (fortran_int)data->columns;
        fortran_int strides = (fortran_int)(data->column_strides/sizeof(float));
        fortran_int one = 1;
        if (strides > 0) {
            FNAME(scopy)(  &len,
                            (void *)src, &one,
                            (void *)dst, &strides);
            FLOAT_conj_vec(len, dst, strides, data);
        }
        else if (strides < 0) {
            /*
            * BLAS _copy assumes dst points to the first element in memory.
            * numpy points it at the first element of the array.
            * We have to compensate.
            */
            FNAME(scopy)(  &len,
                            (void *)src, &one,
                            (void *)(dst + (len-1)*strides), &strides);
            FLOAT_conj_vec(len, dst + (len-1)*strides, strides, data);
        }
        else {
            /*
            * Zero stride has undefined behavior in some BLAS
            * implementations (e.g. OSX Accelerate), so do it
            * manually
            */
            if (len > 0) {
                int j;
                for (j = 0; j < len; ++j) {
                    memcpy((void *)dst, (void *)(src + j), sizeof(float));
                }
                FLOAT_conj_vec(one, dst, strides, data);
            }
        }
    }
}

void
nan_FLOAT_vec(void *dst_in, const LINEARIZE_DATA_t* data)
{
    init_constants();
    float *dst = (float *) dst_in;

    int j;
    ptrdiff_t cs = data->column_strides/sizeof(float);
    for (j = 0; j < data->columns; ++j) {
        *dst = s_nan;
        dst += cs;
    }
}


#line 89

/*********************
*  Complex numbers   *
**********************/

fortran_int
DOUBLE_real_int(fortran_doublereal val)
{
#if 0
    return (fortran_int)val.r;
#else
    return (fortran_int)val;
#endif
}

static NPY_INLINE void
DOUBLE_conj_vec(fortran_int len, double *dst, fortran_int stride,
                const LINEARIZE_DATA_t *data)
{
#if 0
    if (data->conj) {
        FNAME(zlacgv)(&len, (void *)dst, &stride);
    }
#endif
}

/*********************
*  Copying matrices  *
**********************/

void
linearize_DOUBLE_matrix(void *dst_in,
                        const void *src_in,
                        const LINEARIZE_DATA_t* data)
{
    double *src = (double *) src_in;
    double *dst = (double *) dst_in;

    if (dst) {
        int i, j;
        fortran_int columns = (fortran_int)data->columns;
        fortran_int column_strides =
                (fortran_int)(data->column_strides/sizeof(double));
        fortran_int one = 1;
        for (i = 0; i < data->rows; i++) {
            if (column_strides > 0) {
                FNAME(dcopy)(&columns,
                              (void *)src, &column_strides,
                              (void *)dst, &one);
            }
            else if (column_strides < 0) {
                /*
                * BLAS _copy assumes dst points to the first element in memory.
                * numpy points it at the first element of the array.
                * We have to compensate.
                */
                FNAME(dcopy)(  &columns,
                                (void *)((double*)src + (columns-1)*column_strides),
                                &column_strides,
                                (void *)dst, &one);
            }
            else {
                /*
                * Zero stride has undefined behavior in some BLAS
                * implementations (e.g. OSX Accelerate), so do it
                * manually
                */
                for (j = 0; j < columns; ++j) {
                    memcpy((void *)(dst + j), (void *)src, sizeof(double));
                }
            }
            DOUBLE_conj_vec(columns, dst, one, data);
            src += data->row_strides/sizeof(double);
            dst += data->output_lead_dim;
        }
    }
}

void
delinearize_DOUBLE_matrix(  void *dst_in,
                            const void *src_in,
                            const LINEARIZE_DATA_t* data)
{
    double *src = (double *) src_in;
    double *dst = (double *) dst_in;

    if (src) {
        int i;
        fortran_int columns = (fortran_int)data->columns;
        fortran_int column_strides =
            (fortran_int)(data->column_strides/sizeof(double));
        fortran_int one = 1;
        for (i = 0; i < data->rows; i++) {
            if (column_strides > 0) {
                FNAME(dcopy)(  &columns,
                                (void *)src, &one,
                                (void *)dst, &column_strides);
                // DOUBLE_conj_vec(columns, dst, column_strides, data);
            }
            else if (column_strides < 0) {
                /*
                * BLAS _copy/lacgv assume dst points to first element in memory
                * numpy points it at the first element of the array.
                * We have to compensate.
                */
                double *dst_end = dst + (columns-1)*column_strides;
                FNAME(dcopy)(  &columns,
                                (void *)src, &one,
                                (void *)dst_end, &column_strides);
                // DOUBLE_conj_vec(columns, dst_end, column_strides, data);
            }
            else {
                /*
                * Zero stride has undefined behavior in some BLAS
                * implementations (e.g. OSX Accelerate), so do it
                * manually
                */
                if (columns > 0) {
                    memcpy((void *)dst, (void *)(src + (columns-1)), sizeof(double));
                    // DOUBLE_conj_vec(one, dst, column_strides, data);
                }
            }
            src += data->output_lead_dim;
            dst += data->row_strides/sizeof(double);
        }
    }
}

/*
This function does not fill the lower triangle with zeros.
To do that, call zero_DOUBLE_matrix first.
*/
void
delinearize_DOUBLE_triu(void *dst_in,
                        const void *src_in,
                        const LINEARIZE_DATA_t* data)
{
   double *src = (double *) src_in;
   double *dst = (double *) dst_in;

   if (src) {
       int i;
        fortran_int columns = (fortran_int)data->columns;
        fortran_int column_strides =
            (fortran_int)(data->column_strides/sizeof(double));
        fortran_int one = 1;
        for (i = 0; i < data->rows; i++) {
            fortran_int len = fortran_int_min(i + 1, columns);
            if (column_strides > 0) {
                FNAME(dcopy)(  &len,
                                (void *)src, &one,
                                (void *)dst, &column_strides);
            }
            else if (column_strides < 0) {
                /*
                * BLAS _copy assumes dst points to the first element in memory.
                * numpy points it at the first element of the array.
                * We have to compensate.
                */
                FNAME(dcopy)(  &len,
                                (void *)src, &one,
                                (void *)(dst + (len-1)*column_strides),
                                &column_strides);
            }
            else {
                /*
                * Zero stride has undefined behavior in some BLAS
                * implementations (e.g. OSX Accelerate), so do it
                * manually
                */
                if (columns > 0) {
                    memcpy((void *)dst, (void *)(src + (len-1)), sizeof(double));
                }
            }
            src += data->output_lead_dim;
            dst += data->row_strides/sizeof(double);
        }
    }
}

/*
This function does not fill the upper triangle with zeros, or set the diagonal.
To do that, call zero_DOUBLE_matrix first. Unit diagonals can be set with
eye_DOUBLE_matrix.
*/
void
delinearize_DOUBLE_tril(void *dst_in,
                        const void *src_in,
                        const LINEARIZE_DATA_t* data)
{
   double *src = (double *) src_in;
   double *dst = (double *) dst_in;

   if (src) {
       int i;
        fortran_int columns = (fortran_int)data->columns;
        fortran_int column_strides =
            (fortran_int)(data->column_strides/sizeof(double));
        fortran_int one = 1;
        for (i = 0; i < data->rows && i < columns - 1; i++) {
            fortran_int len = columns - i - 1;
            if (len == 0) {
                continue;
            }
            if (column_strides > 0) {
                FNAME(dcopy)(  &len,
                                (void *)(src + i + 1), &one,
                                (void *)(dst + (i+1)*column_strides),
                                &column_strides);
            }
            else if (column_strides < 0) {
                /*
                * BLAS _copy assumes dst points to the first element in memory.
                * numpy points it at the first element of the array.
                * We have to compensate.
                */
                FNAME(dcopy)(  &len,
                                (void *)(src + i + 1), &one,
                                (void *)(dst + (columns-1)*column_strides),
                                &column_strides);
            }
            else {
                /*
                * Zero stride has undefined behavior in some BLAS
                * implementations (e.g. OSX Accelerate), so do it
                * manually
                */
                memcpy((void *)dst, (void *)(src + (columns-1)), sizeof(double));
            }
            src += data->output_lead_dim;
            dst += data->row_strides/sizeof(double);
        }
    }
}

/*********************
*  Filling matrices  *
**********************/

void
nan_DOUBLE_matrix(void *dst_in, const LINEARIZE_DATA_t* data)
{
    init_constants();
    double *dst = (double *) dst_in;

    int i, j;
    ptrdiff_t cs = data->column_strides/sizeof(double);
    for (i = 0; i < data->rows; i++) {
        double *cp = dst;
        for (j = 0; j < data->columns; ++j) {
            *cp = d_nan;
            cp += cs;
        }
        dst += data->row_strides/sizeof(double);
    }
}

void
zero_DOUBLE_matrix(void *dst_in, const LINEARIZE_DATA_t* data)
{
    init_constants();
    double *dst = (double *) dst_in;

    int i, j;
    ptrdiff_t cs = data->column_strides/sizeof(double);
    for (i = 0; i < data->rows; i++) {
        double *cp = dst;
        for (j = 0; j < data->columns; ++j) {
            *cp = d_zero;
            cp += cs;
        }
        dst += data->row_strides/sizeof(double);
    }
}

/*
This function does not fill the off-diagonals with zeros.
To do that, call zero_DOUBLE_matrix first.
*/
void
eye_DOUBLE_matrix(void *dst_in, const LINEARIZE_DATA_t* data)
{
    init_constants();
    double *dst = (double *) dst_in;

    int i;
    ptrdiff_t cs = data->column_strides/sizeof(double);
    for (i = 0; (i < data->rows) && (i < data->columns); i++) {
        *dst = d_one;
        dst += (data->row_strides/sizeof(double)) * (data->output_lead_dim + 1);
    }
}

/*********************
*      Vectors       *
**********************/

void
linearize_DOUBLE_vec(void *dst_in,
                    const void *src_in,
                    const LINEARIZE_DATA_t *data)
{
    double *src = (double *) src_in;
    double *dst = (double *) dst_in;

    if (dst) {
        fortran_int len = (fortran_int)data->columns;
        fortran_int strides = (fortran_int)(data->column_strides/sizeof(double));
        fortran_int one = 1;
        if (strides > 0) {
            FNAME(dcopy)(  &len,
                            (void *)src, &strides,
                            (void *)dst, &one);
        }
        else if (strides < 0) {
            /*
            * Lapack _copy assumes dst points to first element in memory
            * instead of first element of array & tries to compensate.
            * We have to undo that
            */
            FNAME(dcopy)(  &len,
                            (void *)(src + (len-1)*strides), &strides,
                            (void *)dst, &one);
        }
        else {
            /*
            * Zero stride has undefined behavior in some BLAS
            * implementations (e.g. OSX Accelerate), so do it
            * manually
            */
            int j;
            for (j = 0; j < len; ++j) {
                memcpy((void *)(dst + j), (void *)src, sizeof(double));
            }
            DOUBLE_conj_vec(len, dst, one, data);
        }
    }
}

void
delinearize_DOUBLE_vec(void *dst_in,
                     const void *src_in,
                     const LINEARIZE_DATA_t *data)
{
    double *src = (double *) src_in;
    double *dst = (double *) dst_in;

    if (dst) {
        fortran_int len = (fortran_int)data->columns;
        fortran_int strides = (fortran_int)(data->column_strides/sizeof(double));
        fortran_int one = 1;
        if (strides > 0) {
            FNAME(dcopy)(  &len,
                            (void *)src, &one,
                            (void *)dst, &strides);
            DOUBLE_conj_vec(len, dst, strides, data);
        }
        else if (strides < 0) {
            /*
            * BLAS _copy assumes dst points to the first element in memory.
            * numpy points it at the first element of the array.
            * We have to compensate.
            */
            FNAME(dcopy)(  &len,
                            (void *)src, &one,
                            (void *)(dst + (len-1)*strides), &strides);
            DOUBLE_conj_vec(len, dst + (len-1)*strides, strides, data);
        }
        else {
            /*
            * Zero stride has undefined behavior in some BLAS
            * implementations (e.g. OSX Accelerate), so do it
            * manually
            */
            if (len > 0) {
                int j;
                for (j = 0; j < len; ++j) {
                    memcpy((void *)dst, (void *)(src + j), sizeof(double));
                }
                DOUBLE_conj_vec(one, dst, strides, data);
            }
        }
    }
}

void
nan_DOUBLE_vec(void *dst_in, const LINEARIZE_DATA_t* data)
{
    init_constants();
    double *dst = (double *) dst_in;

    int j;
    ptrdiff_t cs = data->column_strides/sizeof(double);
    for (j = 0; j < data->columns; ++j) {
        *dst = d_nan;
        dst += cs;
    }
}


#line 89

/*********************
*  Complex numbers   *
**********************/

fortran_int
CFLOAT_real_int(fortran_complex val)
{
#if 1
    return (fortran_int)val.r;
#else
    return (fortran_int)val;
#endif
}

static NPY_INLINE void
CFLOAT_conj_vec(fortran_int len, COMPLEX_t *dst, fortran_int stride,
                const LINEARIZE_DATA_t *data)
{
#if 1
    if (data->conj) {
        FNAME(clacgv)(&len, (void *)dst, &stride);
    }
#endif
}

/*********************
*  Copying matrices  *
**********************/

void
linearize_CFLOAT_matrix(void *dst_in,
                        const void *src_in,
                        const LINEARIZE_DATA_t* data)
{
    COMPLEX_t *src = (COMPLEX_t *) src_in;
    COMPLEX_t *dst = (COMPLEX_t *) dst_in;

    if (dst) {
        int i, j;
        fortran_int columns = (fortran_int)data->columns;
        fortran_int column_strides =
                (fortran_int)(data->column_strides/sizeof(COMPLEX_t));
        fortran_int one = 1;
        for (i = 0; i < data->rows; i++) {
            if (column_strides > 0) {
                FNAME(ccopy)(&columns,
                              (void *)src, &column_strides,
                              (void *)dst, &one);
            }
            else if (column_strides < 0) {
                /*
                * BLAS _copy assumes dst points to the first element in memory.
                * numpy points it at the first element of the array.
                * We have to compensate.
                */
                FNAME(ccopy)(  &columns,
                                (void *)((COMPLEX_t*)src + (columns-1)*column_strides),
                                &column_strides,
                                (void *)dst, &one);
            }
            else {
                /*
                * Zero stride has undefined behavior in some BLAS
                * implementations (e.g. OSX Accelerate), so do it
                * manually
                */
                for (j = 0; j < columns; ++j) {
                    memcpy((void *)(dst + j), (void *)src, sizeof(COMPLEX_t));
                }
            }
            CFLOAT_conj_vec(columns, dst, one, data);
            src += data->row_strides/sizeof(COMPLEX_t);
            dst += data->output_lead_dim;
        }
    }
}

void
delinearize_CFLOAT_matrix(  void *dst_in,
                            const void *src_in,
                            const LINEARIZE_DATA_t* data)
{
    COMPLEX_t *src = (COMPLEX_t *) src_in;
    COMPLEX_t *dst = (COMPLEX_t *) dst_in;

    if (src) {
        int i;
        fortran_int columns = (fortran_int)data->columns;
        fortran_int column_strides =
            (fortran_int)(data->column_strides/sizeof(COMPLEX_t));
        fortran_int one = 1;
        for (i = 0; i < data->rows; i++) {
            if (column_strides > 0) {
                FNAME(ccopy)(  &columns,
                                (void *)src, &one,
                                (void *)dst, &column_strides);
                // CFLOAT_conj_vec(columns, dst, column_strides, data);
            }
            else if (column_strides < 0) {
                /*
                * BLAS _copy/lacgv assume dst points to first element in memory
                * numpy points it at the first element of the array.
                * We have to compensate.
                */
                COMPLEX_t *dst_end = dst + (columns-1)*column_strides;
                FNAME(ccopy)(  &columns,
                                (void *)src, &one,
                                (void *)dst_end, &column_strides);
                // CFLOAT_conj_vec(columns, dst_end, column_strides, data);
            }
            else {
                /*
                * Zero stride has undefined behavior in some BLAS
                * implementations (e.g. OSX Accelerate), so do it
                * manually
                */
                if (columns > 0) {
                    memcpy((void *)dst, (void *)(src + (columns-1)), sizeof(COMPLEX_t));
                    // CFLOAT_conj_vec(one, dst, column_strides, data);
                }
            }
            src += data->output_lead_dim;
            dst += data->row_strides/sizeof(COMPLEX_t);
        }
    }
}

/*
This function does not fill the lower triangle with zeros.
To do that, call zero_CFLOAT_matrix first.
*/
void
delinearize_CFLOAT_triu(void *dst_in,
                        const void *src_in,
                        const LINEARIZE_DATA_t* data)
{
   COMPLEX_t *src = (COMPLEX_t *) src_in;
   COMPLEX_t *dst = (COMPLEX_t *) dst_in;

   if (src) {
       int i;
        fortran_int columns = (fortran_int)data->columns;
        fortran_int column_strides =
            (fortran_int)(data->column_strides/sizeof(COMPLEX_t));
        fortran_int one = 1;
        for (i = 0; i < data->rows; i++) {
            fortran_int len = fortran_int_min(i + 1, columns);
            if (column_strides > 0) {
                FNAME(ccopy)(  &len,
                                (void *)src, &one,
                                (void *)dst, &column_strides);
            }
            else if (column_strides < 0) {
                /*
                * BLAS _copy assumes dst points to the first element in memory.
                * numpy points it at the first element of the array.
                * We have to compensate.
                */
                FNAME(ccopy)(  &len,
                                (void *)src, &one,
                                (void *)(dst + (len-1)*column_strides),
                                &column_strides);
            }
            else {
                /*
                * Zero stride has undefined behavior in some BLAS
                * implementations (e.g. OSX Accelerate), so do it
                * manually
                */
                if (columns > 0) {
                    memcpy((void *)dst, (void *)(src + (len-1)), sizeof(COMPLEX_t));
                }
            }
            src += data->output_lead_dim;
            dst += data->row_strides/sizeof(COMPLEX_t);
        }
    }
}

/*
This function does not fill the upper triangle with zeros, or set the diagonal.
To do that, call zero_CFLOAT_matrix first. Unit diagonals can be set with
eye_CFLOAT_matrix.
*/
void
delinearize_CFLOAT_tril(void *dst_in,
                        const void *src_in,
                        const LINEARIZE_DATA_t* data)
{
   COMPLEX_t *src = (COMPLEX_t *) src_in;
   COMPLEX_t *dst = (COMPLEX_t *) dst_in;

   if (src) {
       int i;
        fortran_int columns = (fortran_int)data->columns;
        fortran_int column_strides =
            (fortran_int)(data->column_strides/sizeof(COMPLEX_t));
        fortran_int one = 1;
        for (i = 0; i < data->rows && i < columns - 1; i++) {
            fortran_int len = columns - i - 1;
            if (len == 0) {
                continue;
            }
            if (column_strides > 0) {
                FNAME(ccopy)(  &len,
                                (void *)(src + i + 1), &one,
                                (void *)(dst + (i+1)*column_strides),
                                &column_strides);
            }
            else if (column_strides < 0) {
                /*
                * BLAS _copy assumes dst points to the first element in memory.
                * numpy points it at the first element of the array.
                * We have to compensate.
                */
                FNAME(ccopy)(  &len,
                                (void *)(src + i + 1), &one,
                                (void *)(dst + (columns-1)*column_strides),
                                &column_strides);
            }
            else {
                /*
                * Zero stride has undefined behavior in some BLAS
                * implementations (e.g. OSX Accelerate), so do it
                * manually
                */
                memcpy((void *)dst, (void *)(src + (columns-1)), sizeof(COMPLEX_t));
            }
            src += data->output_lead_dim;
            dst += data->row_strides/sizeof(COMPLEX_t);
        }
    }
}

/*********************
*  Filling matrices  *
**********************/

void
nan_CFLOAT_matrix(void *dst_in, const LINEARIZE_DATA_t* data)
{
    init_constants();
    COMPLEX_t *dst = (COMPLEX_t *) dst_in;

    int i, j;
    ptrdiff_t cs = data->column_strides/sizeof(COMPLEX_t);
    for (i = 0; i < data->rows; i++) {
        COMPLEX_t *cp = dst;
        for (j = 0; j < data->columns; ++j) {
            *cp = c_nan;
            cp += cs;
        }
        dst += data->row_strides/sizeof(COMPLEX_t);
    }
}

void
zero_CFLOAT_matrix(void *dst_in, const LINEARIZE_DATA_t* data)
{
    init_constants();
    COMPLEX_t *dst = (COMPLEX_t *) dst_in;

    int i, j;
    ptrdiff_t cs = data->column_strides/sizeof(COMPLEX_t);
    for (i = 0; i < data->rows; i++) {
        COMPLEX_t *cp = dst;
        for (j = 0; j < data->columns; ++j) {
            *cp = c_zero;
            cp += cs;
        }
        dst += data->row_strides/sizeof(COMPLEX_t);
    }
}

/*
This function does not fill the off-diagonals with zeros.
To do that, call zero_CFLOAT_matrix first.
*/
void
eye_CFLOAT_matrix(void *dst_in, const LINEARIZE_DATA_t* data)
{
    init_constants();
    COMPLEX_t *dst = (COMPLEX_t *) dst_in;

    int i;
    ptrdiff_t cs = data->column_strides/sizeof(COMPLEX_t);
    for (i = 0; (i < data->rows) && (i < data->columns); i++) {
        *dst = c_one;
        dst += (data->row_strides/sizeof(COMPLEX_t)) * (data->output_lead_dim + 1);
    }
}

/*********************
*      Vectors       *
**********************/

void
linearize_CFLOAT_vec(void *dst_in,
                    const void *src_in,
                    const LINEARIZE_DATA_t *data)
{
    COMPLEX_t *src = (COMPLEX_t *) src_in;
    COMPLEX_t *dst = (COMPLEX_t *) dst_in;

    if (dst) {
        fortran_int len = (fortran_int)data->columns;
        fortran_int strides = (fortran_int)(data->column_strides/sizeof(COMPLEX_t));
        fortran_int one = 1;
        if (strides > 0) {
            FNAME(ccopy)(  &len,
                            (void *)src, &strides,
                            (void *)dst, &one);
        }
        else if (strides < 0) {
            /*
            * Lapack _copy assumes dst points to first element in memory
            * instead of first element of array & tries to compensate.
            * We have to undo that
            */
            FNAME(ccopy)(  &len,
                            (void *)(src + (len-1)*strides), &strides,
                            (void *)dst, &one);
        }
        else {
            /*
            * Zero stride has undefined behavior in some BLAS
            * implementations (e.g. OSX Accelerate), so do it
            * manually
            */
            int j;
            for (j = 0; j < len; ++j) {
                memcpy((void *)(dst + j), (void *)src, sizeof(COMPLEX_t));
            }
            CFLOAT_conj_vec(len, dst, one, data);
        }
    }
}

void
delinearize_CFLOAT_vec(void *dst_in,
                     const void *src_in,
                     const LINEARIZE_DATA_t *data)
{
    COMPLEX_t *src = (COMPLEX_t *) src_in;
    COMPLEX_t *dst = (COMPLEX_t *) dst_in;

    if (dst) {
        fortran_int len = (fortran_int)data->columns;
        fortran_int strides = (fortran_int)(data->column_strides/sizeof(COMPLEX_t));
        fortran_int one = 1;
        if (strides > 0) {
            FNAME(ccopy)(  &len,
                            (void *)src, &one,
                            (void *)dst, &strides);
            CFLOAT_conj_vec(len, dst, strides, data);
        }
        else if (strides < 0) {
            /*
            * BLAS _copy assumes dst points to the first element in memory.
            * numpy points it at the first element of the array.
            * We have to compensate.
            */
            FNAME(ccopy)(  &len,
                            (void *)src, &one,
                            (void *)(dst + (len-1)*strides), &strides);
            CFLOAT_conj_vec(len, dst + (len-1)*strides, strides, data);
        }
        else {
            /*
            * Zero stride has undefined behavior in some BLAS
            * implementations (e.g. OSX Accelerate), so do it
            * manually
            */
            if (len > 0) {
                int j;
                for (j = 0; j < len; ++j) {
                    memcpy((void *)dst, (void *)(src + j), sizeof(COMPLEX_t));
                }
                CFLOAT_conj_vec(one, dst, strides, data);
            }
        }
    }
}

void
nan_CFLOAT_vec(void *dst_in, const LINEARIZE_DATA_t* data)
{
    init_constants();
    COMPLEX_t *dst = (COMPLEX_t *) dst_in;

    int j;
    ptrdiff_t cs = data->column_strides/sizeof(COMPLEX_t);
    for (j = 0; j < data->columns; ++j) {
        *dst = c_nan;
        dst += cs;
    }
}


#line 89

/*********************
*  Complex numbers   *
**********************/

fortran_int
CDOUBLE_real_int(fortran_doublecomplex val)
{
#if 1
    return (fortran_int)val.r;
#else
    return (fortran_int)val;
#endif
}

static NPY_INLINE void
CDOUBLE_conj_vec(fortran_int len, DOUBLECOMPLEX_t *dst, fortran_int stride,
                const LINEARIZE_DATA_t *data)
{
#if 1
    if (data->conj) {
        FNAME(zlacgv)(&len, (void *)dst, &stride);
    }
#endif
}

/*********************
*  Copying matrices  *
**********************/

void
linearize_CDOUBLE_matrix(void *dst_in,
                        const void *src_in,
                        const LINEARIZE_DATA_t* data)
{
    DOUBLECOMPLEX_t *src = (DOUBLECOMPLEX_t *) src_in;
    DOUBLECOMPLEX_t *dst = (DOUBLECOMPLEX_t *) dst_in;

    if (dst) {
        int i, j;
        fortran_int columns = (fortran_int)data->columns;
        fortran_int column_strides =
                (fortran_int)(data->column_strides/sizeof(DOUBLECOMPLEX_t));
        fortran_int one = 1;
        for (i = 0; i < data->rows; i++) {
            if (column_strides > 0) {
                FNAME(zcopy)(&columns,
                              (void *)src, &column_strides,
                              (void *)dst, &one);
            }
            else if (column_strides < 0) {
                /*
                * BLAS _copy assumes dst points to the first element in memory.
                * numpy points it at the first element of the array.
                * We have to compensate.
                */
                FNAME(zcopy)(  &columns,
                                (void *)((DOUBLECOMPLEX_t*)src + (columns-1)*column_strides),
                                &column_strides,
                                (void *)dst, &one);
            }
            else {
                /*
                * Zero stride has undefined behavior in some BLAS
                * implementations (e.g. OSX Accelerate), so do it
                * manually
                */
                for (j = 0; j < columns; ++j) {
                    memcpy((void *)(dst + j), (void *)src, sizeof(DOUBLECOMPLEX_t));
                }
            }
            CDOUBLE_conj_vec(columns, dst, one, data);
            src += data->row_strides/sizeof(DOUBLECOMPLEX_t);
            dst += data->output_lead_dim;
        }
    }
}

void
delinearize_CDOUBLE_matrix(  void *dst_in,
                            const void *src_in,
                            const LINEARIZE_DATA_t* data)
{
    DOUBLECOMPLEX_t *src = (DOUBLECOMPLEX_t *) src_in;
    DOUBLECOMPLEX_t *dst = (DOUBLECOMPLEX_t *) dst_in;

    if (src) {
        int i;
        fortran_int columns = (fortran_int)data->columns;
        fortran_int column_strides =
            (fortran_int)(data->column_strides/sizeof(DOUBLECOMPLEX_t));
        fortran_int one = 1;
        for (i = 0; i < data->rows; i++) {
            if (column_strides > 0) {
                FNAME(zcopy)(  &columns,
                                (void *)src, &one,
                                (void *)dst, &column_strides);
                // CDOUBLE_conj_vec(columns, dst, column_strides, data);
            }
            else if (column_strides < 0) {
                /*
                * BLAS _copy/lacgv assume dst points to first element in memory
                * numpy points it at the first element of the array.
                * We have to compensate.
                */
                DOUBLECOMPLEX_t *dst_end = dst + (columns-1)*column_strides;
                FNAME(zcopy)(  &columns,
                                (void *)src, &one,
                                (void *)dst_end, &column_strides);
                // CDOUBLE_conj_vec(columns, dst_end, column_strides, data);
            }
            else {
                /*
                * Zero stride has undefined behavior in some BLAS
                * implementations (e.g. OSX Accelerate), so do it
                * manually
                */
                if (columns > 0) {
                    memcpy((void *)dst, (void *)(src + (columns-1)), sizeof(DOUBLECOMPLEX_t));
                    // CDOUBLE_conj_vec(one, dst, column_strides, data);
                }
            }
            src += data->output_lead_dim;
            dst += data->row_strides/sizeof(DOUBLECOMPLEX_t);
        }
    }
}

/*
This function does not fill the lower triangle with zeros.
To do that, call zero_CDOUBLE_matrix first.
*/
void
delinearize_CDOUBLE_triu(void *dst_in,
                        const void *src_in,
                        const LINEARIZE_DATA_t* data)
{
   DOUBLECOMPLEX_t *src = (DOUBLECOMPLEX_t *) src_in;
   DOUBLECOMPLEX_t *dst = (DOUBLECOMPLEX_t *) dst_in;

   if (src) {
       int i;
        fortran_int columns = (fortran_int)data->columns;
        fortran_int column_strides =
            (fortran_int)(data->column_strides/sizeof(DOUBLECOMPLEX_t));
        fortran_int one = 1;
        for (i = 0; i < data->rows; i++) {
            fortran_int len = fortran_int_min(i + 1, columns);
            if (column_strides > 0) {
                FNAME(zcopy)(  &len,
                                (void *)src, &one,
                                (void *)dst, &column_strides);
            }
            else if (column_strides < 0) {
                /*
                * BLAS _copy assumes dst points to the first element in memory.
                * numpy points it at the first element of the array.
                * We have to compensate.
                */
                FNAME(zcopy)(  &len,
                                (void *)src, &one,
                                (void *)(dst + (len-1)*column_strides),
                                &column_strides);
            }
            else {
                /*
                * Zero stride has undefined behavior in some BLAS
                * implementations (e.g. OSX Accelerate), so do it
                * manually
                */
                if (columns > 0) {
                    memcpy((void *)dst, (void *)(src + (len-1)), sizeof(DOUBLECOMPLEX_t));
                }
            }
            src += data->output_lead_dim;
            dst += data->row_strides/sizeof(DOUBLECOMPLEX_t);
        }
    }
}

/*
This function does not fill the upper triangle with zeros, or set the diagonal.
To do that, call zero_CDOUBLE_matrix first. Unit diagonals can be set with
eye_CDOUBLE_matrix.
*/
void
delinearize_CDOUBLE_tril(void *dst_in,
                        const void *src_in,
                        const LINEARIZE_DATA_t* data)
{
   DOUBLECOMPLEX_t *src = (DOUBLECOMPLEX_t *) src_in;
   DOUBLECOMPLEX_t *dst = (DOUBLECOMPLEX_t *) dst_in;

   if (src) {
       int i;
        fortran_int columns = (fortran_int)data->columns;
        fortran_int column_strides =
            (fortran_int)(data->column_strides/sizeof(DOUBLECOMPLEX_t));
        fortran_int one = 1;
        for (i = 0; i < data->rows && i < columns - 1; i++) {
            fortran_int len = columns - i - 1;
            if (len == 0) {
                continue;
            }
            if (column_strides > 0) {
                FNAME(zcopy)(  &len,
                                (void *)(src + i + 1), &one,
                                (void *)(dst + (i+1)*column_strides),
                                &column_strides);
            }
            else if (column_strides < 0) {
                /*
                * BLAS _copy assumes dst points to the first element in memory.
                * numpy points it at the first element of the array.
                * We have to compensate.
                */
                FNAME(zcopy)(  &len,
                                (void *)(src + i + 1), &one,
                                (void *)(dst + (columns-1)*column_strides),
                                &column_strides);
            }
            else {
                /*
                * Zero stride has undefined behavior in some BLAS
                * implementations (e.g. OSX Accelerate), so do it
                * manually
                */
                memcpy((void *)dst, (void *)(src + (columns-1)), sizeof(DOUBLECOMPLEX_t));
            }
            src += data->output_lead_dim;
            dst += data->row_strides/sizeof(DOUBLECOMPLEX_t);
        }
    }
}

/*********************
*  Filling matrices  *
**********************/

void
nan_CDOUBLE_matrix(void *dst_in, const LINEARIZE_DATA_t* data)
{
    init_constants();
    DOUBLECOMPLEX_t *dst = (DOUBLECOMPLEX_t *) dst_in;

    int i, j;
    ptrdiff_t cs = data->column_strides/sizeof(DOUBLECOMPLEX_t);
    for (i = 0; i < data->rows; i++) {
        DOUBLECOMPLEX_t *cp = dst;
        for (j = 0; j < data->columns; ++j) {
            *cp = z_nan;
            cp += cs;
        }
        dst += data->row_strides/sizeof(DOUBLECOMPLEX_t);
    }
}

void
zero_CDOUBLE_matrix(void *dst_in, const LINEARIZE_DATA_t* data)
{
    init_constants();
    DOUBLECOMPLEX_t *dst = (DOUBLECOMPLEX_t *) dst_in;

    int i, j;
    ptrdiff_t cs = data->column_strides/sizeof(DOUBLECOMPLEX_t);
    for (i = 0; i < data->rows; i++) {
        DOUBLECOMPLEX_t *cp = dst;
        for (j = 0; j < data->columns; ++j) {
            *cp = z_zero;
            cp += cs;
        }
        dst += data->row_strides/sizeof(DOUBLECOMPLEX_t);
    }
}

/*
This function does not fill the off-diagonals with zeros.
To do that, call zero_CDOUBLE_matrix first.
*/
void
eye_CDOUBLE_matrix(void *dst_in, const LINEARIZE_DATA_t* data)
{
    init_constants();
    DOUBLECOMPLEX_t *dst = (DOUBLECOMPLEX_t *) dst_in;

    int i;
    ptrdiff_t cs = data->column_strides/sizeof(DOUBLECOMPLEX_t);
    for (i = 0; (i < data->rows) && (i < data->columns); i++) {
        *dst = z_one;
        dst += (data->row_strides/sizeof(DOUBLECOMPLEX_t)) * (data->output_lead_dim + 1);
    }
}

/*********************
*      Vectors       *
**********************/

void
linearize_CDOUBLE_vec(void *dst_in,
                    const void *src_in,
                    const LINEARIZE_DATA_t *data)
{
    DOUBLECOMPLEX_t *src = (DOUBLECOMPLEX_t *) src_in;
    DOUBLECOMPLEX_t *dst = (DOUBLECOMPLEX_t *) dst_in;

    if (dst) {
        fortran_int len = (fortran_int)data->columns;
        fortran_int strides = (fortran_int)(data->column_strides/sizeof(DOUBLECOMPLEX_t));
        fortran_int one = 1;
        if (strides > 0) {
            FNAME(zcopy)(  &len,
                            (void *)src, &strides,
                            (void *)dst, &one);
        }
        else if (strides < 0) {
            /*
            * Lapack _copy assumes dst points to first element in memory
            * instead of first element of array & tries to compensate.
            * We have to undo that
            */
            FNAME(zcopy)(  &len,
                            (void *)(src + (len-1)*strides), &strides,
                            (void *)dst, &one);
        }
        else {
            /*
            * Zero stride has undefined behavior in some BLAS
            * implementations (e.g. OSX Accelerate), so do it
            * manually
            */
            int j;
            for (j = 0; j < len; ++j) {
                memcpy((void *)(dst + j), (void *)src, sizeof(DOUBLECOMPLEX_t));
            }
            CDOUBLE_conj_vec(len, dst, one, data);
        }
    }
}

void
delinearize_CDOUBLE_vec(void *dst_in,
                     const void *src_in,
                     const LINEARIZE_DATA_t *data)
{
    DOUBLECOMPLEX_t *src = (DOUBLECOMPLEX_t *) src_in;
    DOUBLECOMPLEX_t *dst = (DOUBLECOMPLEX_t *) dst_in;

    if (dst) {
        fortran_int len = (fortran_int)data->columns;
        fortran_int strides = (fortran_int)(data->column_strides/sizeof(DOUBLECOMPLEX_t));
        fortran_int one = 1;
        if (strides > 0) {
            FNAME(zcopy)(  &len,
                            (void *)src, &one,
                            (void *)dst, &strides);
            CDOUBLE_conj_vec(len, dst, strides, data);
        }
        else if (strides < 0) {
            /*
            * BLAS _copy assumes dst points to the first element in memory.
            * numpy points it at the first element of the array.
            * We have to compensate.
            */
            FNAME(zcopy)(  &len,
                            (void *)src, &one,
                            (void *)(dst + (len-1)*strides), &strides);
            CDOUBLE_conj_vec(len, dst + (len-1)*strides, strides, data);
        }
        else {
            /*
            * Zero stride has undefined behavior in some BLAS
            * implementations (e.g. OSX Accelerate), so do it
            * manually
            */
            if (len > 0) {
                int j;
                for (j = 0; j < len; ++j) {
                    memcpy((void *)dst, (void *)(src + j), sizeof(DOUBLECOMPLEX_t));
                }
                CDOUBLE_conj_vec(one, dst, strides, data);
            }
        }
    }
}

void
nan_CDOUBLE_vec(void *dst_in, const LINEARIZE_DATA_t* data)
{
    init_constants();
    DOUBLECOMPLEX_t *dst = (DOUBLECOMPLEX_t *) dst_in;

    int j;
    ptrdiff_t cs = data->column_strides/sizeof(DOUBLECOMPLEX_t);
    for (j = 0; j < data->columns; ++j) {
        *dst = z_nan;
        dst += cs;
    }
}



